In [1]:
import numpy as np

In [2]:
# 1-D Array
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
for x in np1:
    print(x)

1
2
3
4
5
6
7
8
9
10


In [6]:
# 2-D Array
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np2:
    print(x)
    for i in x:
        print(i)

[1 2 3 4 5]
1
2
3
4
5
[ 6  7  8  9 10]
6
7
8
9
10


In [9]:
# 3-D Array
np3 = np.array ([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np3:
    print(x)
    for y in x:
        print(y)
        for z in y:
            print(z)

[[1 2 3]
 [4 5 6]]
[1 2 3]
1
2
3
[4 5 6]
4
5
6
[[ 7  8  9]
 [10 11 12]]
[7 8 9]
7
8
9
[10 11 12]
10
11
12


In [11]:
# Use np.nditer() - iterate by single item, whatever how many daimansion is in
for x in np.nditer(np3):
    print(x)


1
2
3
4
5
6
7
8
9
10
11
12
