In [4]:
import numpy as np

In [11]:
# Copy vs. View - copy jest nową tablicą, view jest tylko obrazem oryginału. View zmienia sie wraz ze zmianą obrazu 
# obraz również moze sie zmienić jeśli zmian dokonamy w view. 
np1 = np.array([0,1,2,3,4,5,6,7,8])
np1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:

# Create a view 
np2 = np1.view()
np1[0] = 41
print(np2)
print(np1)

[41  1  2  3  4  5  6  7  8]
[41  1  2  3  4  5  6  7  8]


In [9]:
# Create a copy
np1 = np.array([0,1,2,3,4,5,6,7,8])
np2 = np1.copy()
print (f"NP1 {np1}")
print (f"NP2 {np2}")
np2[0] = 42
print(30*("-"))
print (f"NP1 {np1}")
print (f"NP2 {np2}")

NP1 [0 1 2 3 4 5 6 7 8]
NP2 [0 1 2 3 4 5 6 7 8]
------------------------------
NP1 [0 1 2 3 4 5 6 7 8]
NP2 [42  1  2  3  4  5  6  7  8]
