In [1]:
import numpy as np
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [2]:
list2 = ["JE", 32, [1,2,3], True]
list2

['JE', 32, [1, 2, 3], True]

In [3]:
#Numpy - Numeric Python
# ndarray = n-diamensial array

np1 = np.array([0,1,2,3,4,5,6,7,8,9])
np1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np1.shape # wyświetla ilość elementów w tablicy

(10,)

In [5]:
# Range
np2 = np.arange(10)
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Step
np3 = np.arange(0,10,2) # co drugi element
np3

array([0, 2, 4, 6, 8])

In [8]:
# Zeros
np4 = np.zeros(10)
np4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
# Multidimensial zeros
np5 = np.zeros((2,10)) #dwa wymiary , 10 elementów
np5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
# Full function
np6 = np.full((10),6)
np6

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [13]:
# Multidimensial full
np7 = np.full((2,10),6) # zwraca dwa wymiary , 10 ele., same 6
np7

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])

In [14]:
# Convert Python list to np
my_list = [1,2,3,4,5]
np8 = np.array(my_list)
np8

array([1, 2, 3, 4, 5])

In [15]:
np8

array([1, 2, 3, 4, 5])

In [16]:
np8
my_list

[1, 2, 3, 4, 5]