In [3]:
import numpy as np

In [5]:
# Numpy Universal Function
np1 = np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])

In [8]:
# Square root of each element - pierwiastkowanie
np.sqrt(np1[3:])

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
# Absolute Value - wart. bezwzględna
np.absolute(np1)

array([3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Exponents
np.exp(np1)

array([4.97870684e-02, 1.35335283e-01, 3.67879441e-01, 1.00000000e+00,
       2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [11]:
# Min/Max
np.max(np1)

9

In [12]:
np.min(np1)

-3

In [13]:
# Sign positive or negative
np.sign(np1)

array([-1, -1, -1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [15]:
# Trig sin, cos, tg, ctg, log
np.log(np1[3:])


/tmp/ipykernel_8803/3885940848.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(np1[3:])


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [16]:
np.cos(np1)

array([-0.9899925 , -0.41614684,  0.54030231,  1.        ,  0.54030231,
       -0.41614684, -0.9899925 , -0.65364362,  0.28366219,  0.96017029,
        0.75390225, -0.14550003, -0.91113026])