In [2]:
import numpy as np


In [4]:
# Return from something till the end of the array?
print (np1[3:])

[4 5 6 7 8 9]


In [5]:
# Retutrn negative slices 
print(np1[-3:-1])

[7 8]


In [6]:
# Steps 
np1[1:5:2] # 2-5 w krokach co 2

array([2, 4])

In [7]:
# Steps on the entire array
np1[::2] # wszystkie elementy w kroku co 2

array([1, 3, 5, 7, 9])

In [9]:
# 2D array
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

# Pull out a single item
np2[1,2] # z drugiej tabeli (1) wyciągnij trzeci element (2)


8

In [13]:
# Slice a 2D array
np2[0:1, 1:3] # z tablicy 1 (0:1)- czyli wez pierwszą tablice ale drugiej juz nie, wyciągniej z niej 2 element do 3

array([[2, 3]])

In [15]:
# Slice from  both rows
np2[0:2, 1:3] # wyciągnij z obydwu tablic drugi i trzeci element

array([[2, 3],
       [7, 8]])