In [1]:
import numpy as np

In [6]:
# Create 1-D Numpy Array and Get Shape
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print (np1)
print (np1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [8]:
# Create 2-D Numpy Array and Get Shape, (rows, columns-elements)
np2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print (np2)
print (np2.shape) # Zwraca (2,6) - dwa rzędy i 6 kolumn/elementow

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [10]:
# Reshape 2-D
np3 = np1.reshape(3,4) # zwraca 12 elementów w 3 rzędach po 4 elementy
print (np3)
print (np3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [11]:
# Reshape 3-D
np4 = np1.reshape(2,3,2)
print (np4)
print (np4.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [12]:
# Flatten to 1-D
np5 = np4.reshape(-1)
print (np5)
print (np5.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
