In [1]:
import numpy as np

In [2]:
# np.sort() Numerical
np1 = np.array([6,7,4,1,3,9,2])
np.sort(np1)

array([1, 2, 3, 4, 6, 7, 9])

In [4]:
# np.sort (alphabetical)
np2 = np.array(["John", "Tina", "Eric", "Xavier", "Xaviers"])
np.sort(np2)

array(['Eric', 'John', 'Tina', 'Xavier', 'Xaviers'], dtype='<U7')

In [6]:
# Booleans T/F
np3 = np.array([True, False, False, True])
np.sort(np3)

array([False, False,  True,  True])

In [8]:
# Return a copy not change the orginal
print(np1)
print(np.sort(np1))
print(np1)

[6 7 4 1 3 9 2]
[1 2 3 4 6 7 9]
[6 7 4 1 3 9 2]


In [9]:
# 2D 
np4 = np.array([[6,7,1,9],[8,3,5,0]])
print(np4)
print(np.sort(np4))

[[6 7 1 9]
 [8 3 5 0]]
[[1 6 7 9]
 [0 3 5 8]]
